.gitignore
.travis.yml
Cargo.toml
src/error.rs
src/lib.rs

In order to be stablized macros 1.1 is being tested and eventually
deployed so we can do custom derive. This was implemented in serde
0.8.0. This commit updates github-rs so that it uses the proper
libraries and moving it over to just work on nightly.

Update github-rs to use serde procedural macros

---

src/repositories.rs

Add support for `POST /orgs/:org/repos`

Add post_org_repos

---

src/error.rs
src/git_data.rs
src/json.rs

Consequently this also fixes the issue where certain fields were actually Rust reserved words. I ended up fixing them for the JSON types that used it.

Add ability to get refs from repo

---

src/activity.rs
src/error.rs
src/git_data.rs
src/github.rs
src/json.rs
src/miscellaneous.rs
src/repositories.rs
src/requests.rs
src/users.rs

As part of updating Client to accept media types I also implemented it so that you can set or get fields. This makes is that those modifying Client fields directly code will fail on the next release.

Add media type support and cleanup imports

---

README.md
docs/endpoints.md
examples/getting_started.rs
src/client.rs
src/macros.rs
src/misc/get.rs
src/users/delete.rs
src/users/get.rs
src/users/patch.rs
src/users/post.rs
src/users/put.rs

This commit adds the other request types that were needed for the library to
move forward. It shifts a few things around to get it to work but it works now.
It had to make the return type change to `(StatusCode, Option<Json>)` to work
as I found I was causing unwrapping on empty bodies to happen with things that
aren't returned. This also updates the accompanying docs/examples to work.
Either way maintainers now can implement any endtype without fear. It's now just
implementing all the endpoints!
Closes #24, #25, #26, and #27

Add PUT, POST, PATCH, and DELETE

---

docs/endpoints.md
src/client.rs
src/repos/get.rs
src/users/get.rs
src/util.rs
tests/users.rs

Adds a few more endpoints, beginning the monstrosity that is the /repos/:owner/:repo set of endpoints for get requests. This also cleans up a few stray or outdated comments but the main thing is that custom endpoints were added. Context from the commit itself:
> It might be a while to get the library to a completely usable state. In the
> meantime we should still allow users to be able to use endpoints not covered in
> the code base. On top of that some users might need access to hidden endpoints
> and those are not publically available. This is the solution for these problems.
> While not foolproof since users might mistype the string being used as input it
> still allows flexibility.
>
> The main draw is that users can still use this API as is and as patches come out
> adding new …

Add more endpoints including custom endpoints

---

Cargo.toml
README.md
examples/getting_started.rs
src/client.rs
src/macros.rs
src/misc/get.rs
src/repos/get.rs
src/users/delete.rs
src/users/get.rs
src/users/patch.rs
src/users/post.rs
src/users/put.rs
tests/users.rs

Before we had no good way to expose the event loop to users if they needed it
because doing so would violate the ownership rules. On top of that the lifetime
annotations and problems with the old implementation were a hastle to deal with.
If we limit the need for mutability with a user they have more flexibility due
to the imutability, especially with this API. Functionality will later expose the event loop to users if they want to have access to it.

Switch Core to Rc<RefCell<Core>> in Github Struct

---

README.md
examples/cached_responses.rs
examples/getting_started.rs
src/client.rs
src/headers.rs
src/lib.rs
src/macros.rs
src/repos/get.rs
src/users/delete.rs
src/users/get.rs
src/users/patch.rs
src/users/post.rs
src/users/put.rs
tests/users.rs

This PR adds Headers to the value returned and helper functions to extract certain GitHub specific Header items from it. On top of that it add support for ETags to use cached values if possible. This doesn't go against your GitHub rate limit and is a desirable feature if you're querying a specific bit of data often. Also include a breakage fix from Hyper today. Also fixes an issue where the GitHub struct was moved if called more than once which was undesirable behavior.
Closes #20

Headers and ETags

---

src/client.rs
tests/users.rs

People oftentimes don't want to keep constructing the Event loop just to use it. For users with more advanced needs it has been exposed via a function for them to use.

Expose the Github Core with a method

---

src/client.rs
src/macros.rs

While looking through the Hyper issues I found out that creating a client each
time was a really bad thing to do. This commit changes it so that it's created
once and then referenced when crafting a request for the event loop upon
execution rather than being made each time.

Have Client be internal to the Github struct

---

Cargo.toml

Old document is pointed at [crates.io](https://crates.io/crates/github-rs)

update the link to the documentation

---

Cargo.toml
src/client.rs
src/lib.rs
src/macros.rs

This commit changes the TLS backend from hyper-tls to hyper-rustls,
allowing this package to run on systems without the openssl library
installed (and thus allowing it to run on all systems that Rust can
compile to).

tls: use rustls as tls backend

---

docs/endpoints.md
src/client.rs
src/repos/get.rs
src/repos/post.rs

This adds a bunch of endpoints that are being used in a project I am
working on. You can see what endpoints were added in the
docs/endpoints.md file.
I did not add any endpoints with "ref" as that is a reserved keyword in 
rust and cannot be used directly as a function (that may have to be
worked around eventually).

repos: add new get and post endpoints

---

docs/endpoints.md
src/repos/get.rs

This adds the :username and :username/permission endpoint for
repos/:owner/:repo/collaborators.

repos: add remaining endpoints for collaborators

---

src/client.rs

This allows clients to skip another deserialize step.
---
There is the issue here that non-success results will give an error JSON result rather than `T`. Maybe there should be a `Github` error variant which grabs the message out of these results? See [this code](https://gitlab.kitware.com/utils/rust-gitlab/blob/master/src/error.rs#L40) for Gitlab.

client: allow deserializing into any deserializable type

---

src/client.rs

This allows passing ownership rather than reallocating of the token if
the caller can allow it.

client: perfer ToString rather than AsRef

---

README.md

Thanks for your hard work and open source contributions.
Adds a missing final semicolon for an `extern` statement and adds a
call to `.unwrap()` when creating the initial github-rs client, since
that returns a `Result`.

Small corrections to README code examples

---

src/client.rs
src/lib.rs
src/macros.rs

This is a follow up on 6d33e8a which will allow results to be
automatically deserialize into any deserializable type. It will allow
code like the following:
```rust
struct PullRequest {
title: String,
body: String,
}
let pr: (_, _, PullRequest) = client
.get()
.repos()
.owner(&repo.owner)
.repo(&repo.repo)
.pulls()
.number(&number.to_string())
.execute()
.unwrap();
```

client, macro: deserialize into any deserializable

---

src/lib.rs

This is necessary in order to do comparison against the results of
execute().

lib: expose hyper headers and statuscode

---

Cargo.toml
docs/design.md
examples/cached_responses.rs
examples/getting_started.rs
examples/wrapping_responses.rs
src/client.rs
src/macros.rs
src/misc/get.rs
src/repos/get.rs
src/repos/post.rs
src/users/delete.rs
src/users/get.rs
src/users/patch.rs
src/users/post.rs
src/users/put.rs
tests/users.rs

This changes the macro structure so that instead of using from! and
impl_macro! to create the execute() method, it's done by invoking the
exec! macro. This allows all types with the execute() method to
implement the Executor trait. By implementing a trait, it allows
consuming code to easily pass queries around without having to execute
them up front.
@mgattozzi This is a much more invasive change, but I think it simplifies the macros a bit and having the Executor trait is pretty handy. I threw in a new example to show how I'm using the new functionality.

macros: introduce executor trait

---

.appveyor.yml
.gitignore
.travis.yml
README.md
github-gql-rs/Cargo.toml
github-gql-rs/LICENSE-APACHE
github-gql-rs/LICENSE-MIT
github-gql-rs/README.md
github-gql-rs/src/client.rs
github-gql-rs/src/lib.rs
github-gql-rs/src/mutation.rs
github-gql-rs/src/query.rs
github-gql-rs/tests/users.rs

GitHub's V4 API now uses GraphQL. This subcrate provides an interface to
the the V4 API through GraphQL calls while github-rs remains as is to
interface with the V3 API.
Closes: #2

Create GitHub GQL subcrate

---

src/client.rs
src/macros.rs

This fix address warnings shown by the clippy linting tool:
- https://rust-lang-nursery.github.io/rust-clippy/v0.0.165/index.html#doc_markdown
- https://rust-lang-nursery.github.io/rust-clippy/v0.0.165/index.html#clone_on_ref_ptr
I have tested my changes (using an auth_token) and the tests are passing.
ref: https://github.com/rust-lang-nursery/rust-clippy

fix (client and macros): fixed clippy warnings

---

.appveyor.yml

There was a weird EOF issue that kept coming up on appveyor breaking the
build. This changes it to not have it at all.

Remove caching on appveyor

---

docs/endpoints.md
src/repos/get.rs

To keep this review-able I'll be doing this PR in parts. The first part contains
- commits-by-ref endpoints
- top level leaf endpoints
- branch endpoints
Tracking issue: #94

Add non-preview repo GET endpoints, part 1

---

Cargo.toml

This includes a bump to rustls 0.12.0 which has a fix for recent
compilation issues.

cargo: update hyper-rustls to 0.12.0

---

.appveyor.yml
.travis.yml
Cargo.toml
README.md
github-gql-rs/Cargo.toml
github-gql-rs/src/client.rs
github-gql-rs/src/lib.rs
src/client.rs
src/errors.rs
src/lib.rs
src/macros.rs

Adds default feature `rustls`; `native-tls` support is enabled by feature `rust-native-tls`. The feature name is chosen because `native-tls` is already taken by the crate, which must be included in order to generate the necessary `error_chain` `foreign_link`.
Fixes #133.

Add optional native-tls support

---

.gitignore
docs/endpoints.md
src/client.rs
src/notifications/delete.rs
src/notifications/get.rs
src/notifications/patch.rs
src/notifications/put.rs
tests/notifications.rs

Fixes #92 
To avoid conflicts in src/client.rs, this is based on top of my search commits. If you'd prefer me to rebase it onto master instead, that's easy enough.
Also, since there weren't too many endpoints in total, I put everything into one commit. If you think it'd be easier to review by request type (GET - 3 endpoints; PUT - 2 endpoints; DELETE - 1 endpoint; PATCH - 1 endpoint), I can split it up into four separate commits.

Add non-preview notifications endpoints

---

src/orgs/get.rs

Not sure if this has changed or if the orgs endpoints has never worked or what, but for me it did not work with `organizations` but it did work with `orgs`.

Github endpoint is orgs, not organizations

---

github-gql-rs/Cargo.toml
github-gql-rs/README.md
github-gql-rs/src/query.rs
github-gql-rs/tests/users.rs

Implemented internal escaping for json. Current version needs to think about escaping json manually (quotations, new lines) which is error prone and hard to use. Changing escaping to internal implementation will allow to just paste graphql requests and have necessary characters be implicitly escaped when passed inside json.
It is a breaking change (changed from explicit to implicit escaping) so I upped a version to 0.0.2

implemented internal escaping

---

README.md

`0.6` currently does not work. See: https://github.com/github-rs/github-rs/issues/163. 
Upgrading to `0.7` solves the above problem, so should be recommended in `README.dm` now.

Update library version recommended in README.md
